name: Deploy website to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/pages.yml'
      - 'website/**'
      - 'docs/**'
      - 'mkdocs.yml'
      - 'ani-cli-gui/build/icon.png'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs & Build Docs
        run: |
          pip install mkdocs-material
          mkdocs build --site-dir website/dist/docs

      - name: Build main static site
        run: node website/build.mjs

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: website/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: Deploy GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4